### PR TITLE
Add charge to stoichiometry method (and test)

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by langner** [comment]
The convenience method allows one to do this:

```
cclib/data/Gaussian/basicGaussian09$ python
>>> import cclib
>>> data = cclib.parser.ccopen('water_mp4.log').parse()
>>> data.stoichiometry()
'O1H2'
```

**Comment by jaimergp** [comment]
That's cool! One thing though: do we want to be explicit when there's only one atom of a given element? I find the "1" after the O really weird...

**Comment by langner** [comment]
Here you go. Also made it compliant with the Hill system, which I think is the standard.

**Comment by langner** [comment]
Having it be a property makes it work more like an attribute:

```
cclib/data/Gaussian/basicGaussian09$ python
>>> import cclib
>>> data = cclib.parser.ccopen('water_mp4.log').parse()
>>> data.stoichiometry
'O1H2'
```

**Comment by jaimergp** [comment]
LGTM!

**Pull request merged**
