### PR TITLE
Replace stoichiometry with a method

### PR DESCRIPTION
**Pull request by langner**
This is for cclib/cclib#295

### CODE REVIEW

**Comment by jaimergp** [comment]
I like the proposal! However, my numpy.ndarrays do not feature a .count() method. Which version is yours?

I got this one to work:

``` python
import cclib
import numpy
def stoichoimetry(atomnos):
    """Return the stoichemistry of the object."""
    pt = cclib.parser.utils.PeriodicTable()
    formula = []
    unique, counts = numpy.unique(atomnos, return_counts=True)
    counter = {u:c for (u,c) in zip(unique, counts)}
    for ano in sorted(unique, reverse=True):
        count = counter[ano] if counter[ano] > 1 else ''
        formula.append('{}{}'.format(pt.element[ano], count))
    return ''.join(formula)
```

**Comment by jaimergp** [comment]
However, this is not the same as Gaussian's!

For example, I have a Gold complex with this stoichiometry: `C17H26AuN2(1+)`, but this approach outputs `AuN2C17H26`. While we could add charges, the sorting is non-trivial I think...

**Comment by langner** [comment]
> I like the proposal! However, my numpy.ndarrays do not feature a .count() method. Which version is yours?

You are right, I forgot `atomnos` is an ndarray. I just commited a fix, but you can also just incorporate your fix.

**Comment by langner** [comment]
> However, this is not the same as Gaussian's!

If you are concerned about the order of elements, we can add some heuristics to the code. Do you have a good reference for how the formula should be formed?

> For example, I have a Gold complex with this stoichiometry: C17H26AuN2(1+), but this approach outputs AuN2C17H26. While we could add charges, the sorting is non-trivial I think...

We can add the charge, just use the `charge` attribute.

**Pull request merged**
